# Generated by Django 5.2.8 on 2025-11-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='fecha_actividad',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='musica_activada',
            new_name='sonido',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='tipo_actividad',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='dificultad_preferida',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='notificaciones',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='sonido_activado',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='tema_oscuro',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='juego',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='puntaje',
            name='fecha_puntaje',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='dificultad',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
